# Generated by Django 5.1 on 2024-09-29 17:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_name', models.CharField(max_length=60)),
                ('company_name', models.CharField(max_length=60)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('img_url', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('detections', models.IntegerField()),
            ],
            options={
                'db_table': 'threats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='draft', max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 29, 17, 56, 2, 215990))),
                ('formed_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('final_price', models.IntegerField(null=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_threats', to='threats.request')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threat')),
            ],
            options={
                'db_table': 'requests_threats',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('request', 'threat'), name='unique_request_threat')],
            },
        ),
    ]
