# Generated by Django 5.1 on 2024-09-17 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0002_alter_request_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 13, 32, 20, 662387)),
        ),
    ]
