# Generated by Django 5.1 on 2024-09-22 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0004_alter_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestthreat',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 15, 7, 51, 736663)),
        ),
    ]
