# Generated by Django 4.2.4 on 2024-09-22 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='draft', max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 22, 15, 50, 44, 830868))),
                ('formed_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('creator', models.CharField(default='lexcf', max_length=50)),
                ('moderator', models.CharField(max_length=50, null=True)),
                ('final_price', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_name', models.CharField(max_length=60)),
                ('company_name', models.CharField(max_length=60)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('img_url', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('detections', models.IntegerField()),
            ],
            options={
                'db_table': 'threats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_threats', to='monitoring.request')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.threat')),
            ],
            options={
                'db_table': 'requests_threats',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='requestthreat',
            constraint=models.UniqueConstraint(fields=('request', 'threat'), name='unique_request_threat'),
        ),
    ]
