# Generated by Django 4.2.4 on 2024-09-25 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_request_created_at_alter_request_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestthreat',
            name='comment',
        ),
        migrations.AddField(
            model_name='requestthreat',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 36, 18, 889506)),
        ),
    ]
