# Generated by Django 4.2.4 on 2024-09-30 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_remove_requestthreat_comment_requestthreat_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 16, 14, 25, 977569)),
        ),
    ]
