# Generated by Django 4.2.4 on 2024-10-27 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_alter_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestthreat',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 16, 51, 28, 652371)),
        ),
    ]
